spring:
  profiles: dev
  application:
    name: API-CALLCENTER
server:
  port: 7201
threadConfiguration:
  corePoolSize: ${CORE_POOL_SIZE:3}
  maxPoolSize: ${MAX_POOL_SIZE:3}
  queueCapacity: ${QUEUE_CAPACITY:10}
callConfiguration:
  maxTime: ${CALL_MAX_TIME:10000}
  minTime: ${CALL_MIN_TIME:5000}
---
spring:
  profiles: test
  application:
    name: API-CALLCENTER
threadConfiguration:
  corePoolSize: 3
  maxPoolSize: 3
  queueCapacity: 10
callConfiguration:
  maxTime: 10
  minTime: 10

